### ISSUE TITLE
request:  filter by month & day

### ISSUE THREAD

**Issue by Skullduggeryism** [marcelja/facebook-delete#1]
This is the best FB scrubber I've found so far, it's fast, and it works.  How difficult would it be to allow filtering by month and day?

**Comment by marcelja** [comment]
I can look into that. It should be easy if the entries in the activity log have timestamps.

**Comment by BTolbert65** [comment]
Any updates to address selecting the day?  e.g. I'd like to delete everything older than 10-14 days.

**Comment by marcelja** [comment]
I added a filter functionality for months on master. I don't think that I want to implement a day filter.
