### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by dbaccello** [marcelja/facebook-delete#10]
`xxxxxxxxx@xxxx:~/Downloads$ ./deleter-linux 
? Please type your email xxxxxxxxxxxxxxxx
? Please type your password *************
Attempting Login...
panic: Failed to login

goroutine 1 [running]:
main.newFbLogin(0xc000097010, 0x0)
	/Users/marceljankrift/facebook-delete/deleter.go:102 +0xdd
main.main()
	/Users/marceljankrift/facebook-delete/deleter.go:394 +0x42`

**Comment by marcelja** [comment]
Are you able to login on https://mbasic.facebook.com/? Sometimes facebook wants some additional information for security purpose. And do you have 2FA disabled?

**Comment by rworang** [comment]
> Are you able to login on https://mbasic.facebook.com/? Sometimes facebook wants some additional information for security purpose. And do you have 2FA disabled?

I'm having the same issue, I first tried on Win 10 and it just exited, I then tried it on Ubuntu-20.04 using WSL and I get the same response as original poster here.

I don't have 2FA and am able to login on the mbasic URL.

**Comment by marcelja** [comment]
Hm, yes, I'm also having the problem. When I'm observing the network requests while logging in using a browser, it looks like the old login URL and parameters are still used.

But something was definitely changed. It's probably related to this saved account selecting. I can not remember that this existed when I implemented this. I'll try to look into this in the next days.

**Comment by rworang** [comment]
The error also references line 102 so it might be the cookiejar thing

**Comment by marcelja** [comment]
I just tried to understand the login process. What I saw is that everytime I'm deleting the cookies in my browser and login with the correct email and password, it responds with
```
Your Request Couldn't be Processed
There was a problem with this request. We're working on getting it fixed as soon as we can
```
The response headers include some new cookies. Afterwards, I'm able to login successfully.

I didn't manage to login using curl/go yet. They probably expect some additional request headers or form data.

**Comment by marcelja** [comment]
Ok, I managed to login using curl.

**Comment by marcelja** [comment]
Login should work now. I also updated the binaries.

**Comment by rworang** [comment]
It seems to be working now, thanks for the fix!

**Comment by dbaccello** [comment]
Thanks it also works to me on Ubuntu 20.10
