### ISSUE TITLE
Attempting to login... then cmd shuts down.

### ISSUE THREAD

**Issue by deroverda** [marcelja/facebook-delete#11]
Hi, using win 10, downloaded lastest win exe file. typed my login credentials and got the message "attempting to login" that is displayed like 1 second before cmd shuts down. is it not working or am I doing something wrong? 

cheers!

**Comment by rworang** [comment]
I'm having the same issues

**Comment by marcelja** [comment]
Yes, this probably caused by some kind of API change, see #10

**Comment by deroverda** [comment]
@marcelja Roger that. I'll keep an eye on how this develops. You can close this issue (not possible using mobile app).
