### ISSUE TITLE
Comment & Likes not deleting

### ISSUE THREAD

**Issue by azizmoalim** [marcelja/facebook-delete#12]
It seems my comments and likes are not deleting when using this tool. Anyone else experiencing this issue?

**Comment by MichaelMallett** [comment]
Are you getting any feedback? I don't get anything, it gives me options of years, months, type and then I get nothing. Checking the activity log on fb nothing has been deleted. A verbose mode or some logging would be handy

**Comment by azizmoalim** [comment]
> Are you getting any feedback? I don't get anything, it gives me options of years, months, type and then I get nothing. Checking the activity log on fb nothing has been deleted. A verbose mode or some logging would be handy

No feedback. As an example, I ask the program to delete all comments and likes for the year 2015, the program closes as if it was successful without deleting anything.

**Comment by marcelja** [comment]
It shouldn't happen that you get no output. Could you send the entire output of the program? That could help to understand why it's not collecting entries.
