### ISSUE TITLE
Login appaears to be broken.

### ISSUE THREAD

**Issue by ir0nh3at** [marcelja/facebook-delete#13]
deleter.go seems to not be logging in correctly.  Of course I sanity checked my password.  Also looked at the URLs set and they seem to be up.  I haven't tried firing up burp yet, but I figured I'd hit up the community first.  Thoughts?  Thanks!

? Please type your email <redacted>
? Please type your password ***********************
Attempting Login...
panic: Failed to login

goroutine 1 [running]:
main.newFbLogin(0xc000073040, 0xc00009fec8)
	/root/go/src/github.com/marcelja/facebook-delete/deleter.go:104 +0xe3
main.main()
	/root/go/src/github.com/marcelja/facebook-delete/deleter.go:444 +0x45
exit status 2

**Comment by ir0nh3at** [comment]
Tested with your debug_login.sh and confirmed it's broken.

**Comment by marcelja** [comment]
I'll investigate later. Probably they changed the login again.

**Comment by marcelja** [comment]
For me, the login works with both deleter.go and debug_login.sh. You don't have 2FA enabled (just to make sure)?

Could you please login on https://mbasic.facebook.com/ and describe whether the login fails on the first try and works when trying again?

**Comment by ir0nh3at** [comment]
Sorry about the delay in responding.  We had a weather event the other day and I've been stuck tethered to my cell phone with one bar since...

I'm thoroughly embarrassed that I didn't check my MFA status.  I thought I had it disabled.  When I checked the URL as you describe I was prompted for another factor.  Sorry for the false issue and not doing my homework.  Thanks for the response.

**Comment by ir0nh3at** [comment]
Sorry for the boomerang.  I was mistaken - I don't have MFA on, FB just thought it was suspicious.  I tried using an OTP and an App Password and both are triggering a password reset after a few attempts.  Super frustrating.  If you have any other ideas I'd love to hear them, otherwise I'll keep monkeying with it.  Thanks!

**Comment by marcelja** [comment]
What's an App Password? The program is only supporting a normal username and password

**Comment by ir0nh3at** [comment]
Facebook has the ability to create passwords for apps you don't want to provide your real password to - I tried that in desperation *after* it  failed with my regular credentials.  That's a red herring, forget I ever said anything.  

It's weird, for some reason Facebook must think there's something shady going on since the login fails and then it makes me change the password after three attempts, but I can't get a handle on why.

On the plus side, after manually exporting my cookies from firefox and importing them into .go-cookies, everything seems to be working, so I'll take that as "good enough."  Thanks for making the tool, and I appreciate you taking a look at my problem.
