### ISSUE TITLE
Delete no longer working

### ISSUE THREAD

**Issue by drpoutine** [marcelja/facebook-delete#15]
Just did a run. Program reports like everything is being deleted but nothing is removed when i check the activity log. Might have something to do with a new layout for activity log on facebook. Program isnt aware its failing?

PS: might just be getting archived instead of being deleted :|

**Comment by Dark3n89** [comment]
> Just did a run. Program reports like everything is being deleted but nothing is removed when i check the activity log. Might have something to do with a new layout for activity log on facebook. Program isnt aware its failing?
> 
> PS: might just be getting archived instead of being deleted :|

bcs  FB make now all trought unique links, but you can simply scan for words with jquery
example :  $("div[role*='button']:visible:contains('OK'):first").click();

**Comment by marcelja** [comment]
Thank you! I guess we could store and call the unique links as well. I could look into this on the weekend

**Comment by marcelja** [comment]
I just checked the script and it was able to unlike elements for my account. It doesn't look to me that something changed. Which categories did you try to delete activity from?

**Comment by marcelja** [comment]
I found something that resulted in not finding all elements in the activity log. It's fixed in the master branch and I updated the binaries.

**Comment by Dark3n89** [comment]
> I found something that resulted in not finding all elements in the activity log. It's fixed in the master branch and I updated the binaries.

i mean this method click examples... delete by words are gone forever ... i think

if($("span:visible:contains('This Page Isn't Available Right Now'):first").length > 0) {
				 myreload2();
			}
			if ($("span:visible:contains('error'):first").length > 0) {
				$("div[role*='button']:visible:contains('OK'):first").click();
			}

**Comment by marcelja** [comment]
I don't really understand what you mean, but I just used my script and deleted 400 elements and my activity log is empty for that year

**Comment by charlesangus** [comment]
I'm finding it's not deleting comments, searches, or likes. At least, not reliably. Running it over a year with comments results in 0 elements found.

**Comment by charlesangus** [comment]
Ah - looks like I've been locked out. Maybe a rate-limit option (Going to the mbasic activity log displays "You’re Temporarily Blocked - It looks like you were misusing this feature by going too fast. You’ve been temporarily blocked from using it.")

**Comment by marcelja** [comment]
I could also search for that string in the responses to be able to print this information while the script is running
