### ISSUE TITLE
Add rate-limit option

### ISSUE THREAD

**Issue by charlesangus** [marcelja/facebook-delete#16]
Not sure what the speed Facebook wants us to run at is, but deleting several thousand items got me locked out.

Custom rate-limit option would be swell!

**Comment by marcelja** [comment]
Did you get rate-limited during the element search or during the deletion process? Because for the searching, it's requesting one by one. We could add an option to wait between requests.

**Comment by charlesangus** [comment]
I'm afraid I'm not certain if it was during search or delete, and I closed that terminal so I don't have the log anymore (d'oh).
