### ISSUE TITLE
App crashes on attempting login

### ISSUE THREAD

**Issue by bagaweb** [marcelja/facebook-delete#19]
After typing email & password, the app crashes.
I'm on Windows 10 x64, no antivirus installed.
Facebook asked me to change the password after this.

**Comment by marcelja** [comment]
I'd try to change the password and run the application again with the new password

**Comment by bagaweb** [comment]
Tried again, no luck, same problem as before.

**Comment by marcelja** [comment]
I think that facebook has some mechanisms to detect automated or suspicious actions. That could result in locking the account which would make the script fail.

It would be interesting to debug the login process. I have a script called `debug_login.sh` in this repo. This will probably not run on Windows. If you have some Linux subsystem, you could try running that script in there. Then we could see if the general idea of the login is working for you.

**Comment by bagaweb** [comment]
Unfortunately I do not have Linux at the moment even though it's on my checklist to get rid of Windows sooner or later.
Anyway I gave your tool another try, still crashed after attempting login.
Thanks for your support.

**Comment by replete** [comment]
I had to disable 2FA to make it work

**Comment by bagaweb** [comment]
Any fix?

**Comment by marcelja** [comment]
No, I would need more information to understand the problem. I think that we should wait until someone has the same issue and can provide some debugging.

**Comment by replete** [comment]
It's 2FA. Discount 2FA fixed the issue for me. But I couldn't delete anyway
from API limits...

**Comment by marcelja** [comment]
What kind of API limits did you experience?

**Comment by replete** [comment]
> What kind of API limits did you experience?

`0panic: ratelimited, please open https://mbasic.facebook.com and navigate to your activity log to see more information.`

Upon navigating to the 'Activity Log' I am greeted with this error on Facebook:
![image](https://user-images.githubusercontent.com/812139/124482409-2549d180-dda1-11eb-931a-52e983d4a4c9.png)
