### ISSUE TITLE
Virustotal scan

### ISSUE THREAD

**Issue by vemfanvet** [marcelja/facebook-delete#21]
https://www.virustotal.com/gui/file/1692e066a72c3659ea3d5b2716ddf72daf689308cd124bbd51d092318b2227dc/detection

Doesn't look that good. Any explanation to these results?

**Comment by marcelja** [comment]
You should always be aware that people in the internet could theoretically put whatever they want into the binaries (independent of any virus scan result). If you don't trust it, feel free to read the code and compile it from source.
