### ISSUE TITLE
 cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by danieltornroos** [marcelja/facebook-delete#34]
I get this error: "cannot execute binary file: Exec format error"
after trying to run the executable on my Vero 4K+ (OSMC).
Do I have some dependancy missing?

**Comment by danieltornroos** [comment]
Yes it would be ARM based, would it help if I compile it myself, or the source code would need to be changed?

**Comment by marcelja** [comment]
Yep, you can compile it yourself. I'll try to adjust the build script to add ARM binaries.
