### ISSUE TITLE
Change default rate limit

### ISSUE THREAD

**Issue by jcktm** [marcelja/facebook-delete#41]
Default rate limit is making requests too fast:

<img width="628" alt="Screen Shot 2021-11-12 at 7 52 08 am" src="https://user-images.githubusercontent.com/9440750/141367492-6c7bf290-1c68-4671-8d16-bf5e7c168594.png">

**Comment by marcelja** [comment]
I think that most users are not getting temporarily blocked without rate limiting.

**Comment by rTeamWork** [comment]
> I think that most users are not getting temporarily blocked without rate limiting.

Do you have any idea why some of us get banned even with a ridiculously high rate limit?

**Comment by marcelja** [comment]
Not sure how they detect automated requests. Maybe via the user agent or number of parallel requests...
