### ISSUE TITLE
Type *cookiejar.Jar has no field or method Save

### ISSUE THREAD

**Issue by AlexKalopsia** [marcelja/facebook-delete#49]
When I try and `go run deleter.go` , the terminal returns `req.jar.Save undefined (type *cookiejar.Jar has no field or method Save)`.

From the [docs](https://pkg.go.dev/net/http/cookiejar) it looks as if cookiejar doesn't have a Save method, so I am a bit confused.

**Comment by marcelja** [comment]
It's using persistent-cookiejar which has the Save function: https://github.com/juju/persistent-cookiejar#func-jar-save

What's you go version? Did you run `go install` before?

**Comment by AlexKalopsia** [comment]
Ok, found out that this was an issue with VS Code, which was automatically changing `"github.com/juju/persistent-cookiejar"` to `"net/http/cookiejar"` whenever I pressed `Ctrl+S`. 

Adding the following to language specific `settings.json` fixed the issue

```
"[go]": {

        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": false
        },
    },
    "go.formatTool": "gofmt",
```

Thanks for the help!
