### ISSUE TITLE
Request: Implement option to delete facebook's activity log

### ISSUE THREAD

**Issue by derdjme** [marcelja/facebook-delete#9]
After deleting, there are still all informations left in facebook's activity log. Would be nice if this could be deleted, too.

**Comment by marcelja** [comment]
This sounds like something did not work. What categories did you try to delete? Did you use the binaries or the current master?

**Comment by derdjme** [comment]
Yes I did. I did select everything that was available. What I found is that very old entries (2010, 2011) seemed to be different. When manually deleting them facebook offered me to "dislike" instead of the usally "delete". Apart from that some entries about where I lived and where I "moved to" had to be delted manaually, too.

**Comment by marcelja** [comment]
Oh yes, these entries are very likely not covered. The dislike action could maybe be added by appending "dislike" to this list:
https://github.com/marcelja/facebook-delete/blob/4e63e37e8f8eef54487e956ace950358a8ac5355/deleter.go#L46

It depends on how the "dislike" URL looks, though.
